### ISSUE TITLE
Set up Kibana

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-Migration#16]
https://kibana-openshift-logging.apps.silver.devops.gov.bc.ca/

When you first log into Kibana you need to create your search index.

Index pattern: `app*`
Timestamp field name: `@timestamp`

![image](https://user-images.githubusercontent.com/24236108/98299796-1f2ef700-1f6d-11eb-99bf-7bb608a7dc8d.png)
![image](https://user-images.githubusercontent.com/24236108/98299832-2d7d1300-1f6d-11eb-8d0a-a90a98ece48f.png)

**Comment by david-agahchen** [comment]
There is a bug reported opened with RedHat re Kibana corrupting users security index settings (see https://bugzilla.redhat.com/show_bug.cgi?id=1902112 for more details.)

The workaround in the mean time is to request the removal on your Kibana settings file (provide your GitHub id) via Rocket.Chat (e.g., #devops-ocp4-migration or #devops-operations channel).

**Comment by matthieu-foucault** [comment]
How long is creating an index pattern expected to take? I followed the steps above, and can only see this:
![image](https://user-images.githubusercontent.com/2684022/117863498-b0e32e00-b248-11eb-9933-d2e8688a9831.png)
