### ISSUE TITLE
Artifactory service

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/OpenShift4-Migration#24]
OCP4 supports our on-prem Caching Repository.

RocketChat Reference(s):
- https://chat.pathfinder.gov.bc.ca/channel/devops-ocp4-migration?msg=JGWNaixvNHH9pNHCs

For further details:
- https://github.com/BCDevOps/developer-experience/blob/master/apps/artifactory/DEVHUB-README.md

**Comment by caggles** [comment]
Quick reference on the intended use of Artifactory:

Caching repos are available right now and all teams are encouraged to use these.

Private repos are going to be available soon and will allow teams to push their own images and other artifacts to artifactory. We encourage teams to push only prod (or prod-ready) images to their private repos. So build on the OCP integrated registry, and then push your image to artifactory once you're ready for prod.

There are a number of reasons for encouraging this pattern, which will be updated in our documentation very soon as well!
