### ISSUE TITLE
No more *.bcgov by default

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/OpenShift4-Migration#26]
Unlike OCP3, there are no default `*.bcgov` routes.

RocketChat Reference(s):
- https://chat.pathfinder.gov.bc.ca/channel/devops-ocp4-migration?msg=d9z6KdTaAxKtkgYDK

**Comment by jleach** [comment]
@garywong-bc I created #48 to document a convo we had with AG/JAG about this. I creating a wildcard `*.bcgov` for the new clusters in favour of teams using a vanity domain like `mycoolapp.nrm.bcgov` and just pointing that via a DNS `CNAME` record to `aps.silver.gov.bc.ca` or the front-door IP. That ticket also comments on how to better secure the route.
