### ISSUE TITLE
Coordinating migration of changes of DNS Vanity URLs

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/OpenShift4-Migration#30]
When re-pointing existing DNS names,  a best practice is to reduce TTL and to collaborate w OCIO to schedule during off-hours.

RocketChat Reference(s):
- https://chat.pathfinder.gov.bc.ca/channel/devops-ocp4-migration?msg=6ZEZPJPmNLasgQf3r

To find the IP of the OCP4 VIP (point your vanity URL DNS entry to it), please get access to https://docs.pathfinder.gov.bc.ca/s/bn6v0ac6f9gue7hhirbg/protected-platform-services/d/bsg9q3nu3u14r4kded80/ocp-4-platform-network-topology and look up the `Ingress VIP` IP Address

**Comment by gil0109** [comment]
I also worked with OCIO/CITZ IMB to get access to my domain (servicebc.gov.bc.ca) to adjust DNS myself at anytime for my specific Domain.  Works great...

If you use/have access to wildcard cert.. this is great.

Web App is called Remedy.
