### ISSUE TITLE
Pending Firewall rule to allow connection to/from OCP3

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/OpenShift4-Migration#33]
Until the pending FW rule to allow OPC3 to SILVER is implemented, you will be unable to connect from the Pathfinder cluster to Silver.

RocketChat Reference(s):
- https://chat.pathfinder.gov.bc.ca/channel/devops-ocp4-migration?msg=pwPG5tjBmhE67m72k

For further details:
- https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/427

**Comment by StevenBarre** [comment]
Firewall rule has been implemented.
