### ISSUE TITLE
How to Request a Resource Quota Increase for a Namespace in OCP 4? 

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/OpenShift4-Migration#36]
All project sets in the new OCP 4 Platform are provisioned by default with a "small" resource quota size that includes a certain amout of CPU, RAM and Storage.  The amount of resources within each quota size - small, medium and large are as follows:

**CPU/RAM/Storage long-running workload quotas (per namespace)**:
* **Small (Default)**:  
CPU: 4 cores as request, 8 cores as limit
RAM: 16GBs as request, 32GBs as limit
20 PVC count , 50Gbs overall storage with 25 GBs for backup storage

* **Medium: (needs to be requested and justified)**:
Long-running workload quotas:
CPU: 8 cores as request, 16 cores as limit
RAM: 32GBs as request, 64GBs as limit
Medium: 40 PVC count , 100Gbs overall storage with 50 GBs for backup storage

* **Large: (needs to be requested and justified):**
Long-running workload quotas:
CPU: 16 cores as request, 32 cores as limit
RAM: 64GBs as request, 128GBs as limit
Large: 60 PVC count , 200Gbs overall storage with 100 GBs for backup storage 

If you find that the new default allocations are insufficient, you can request a quota increase **for the entire project set** in the Project Registry (currently this feature is only available to the requestors of the project set provisioning as part of the project edit funtionality, it will be available to POs/Tech Leads in Jan 2021).  

**We currently do not support quota increases for a specific resource (i.e. just RAM, or just CPU, or just Storage) or for a specific namespace (i.e. prod only).**  Teams requiring more resources in any of the 3 resource categories such as CPU/RAM/Storage in any of the 4 namespaces (dev, test, tool or prod), will have to submit a standard quota increase request through the Project Registry.  The upgrade path will only be available in this order: from small -> medium -> large. You cannot skip medium and upgrade from small to large.

Once the quota increase request is approved (see the approval process below), all 4 namespaces in a project set will be upgraded to the next quota size which includes a double amount of resources in all 3 categories.

*Example: If your prod namespace needs more storage and you request a standard quota increase from small to medium, the resource allocations for all 4 of your namespaces will be upgraded to the medium size quota as per the OCP 4 quota definition.*

**Quota increase approval process**

When requesting a quota increase from small to medium,  follow the process for request a quota increase as described [here](https://developer.gov.bc.ca/Need-more-quota-for-OpenShift-project-set).

When requesting a quota increase from medium to large, book a 30 min meeting with the Platform Services Team (send the invite to @mitovskaol and she will be pull in team's operations experts as needed). The Platform Services Team will be looking for an overview of the application design and architecture that clearly demonstrate why more resources are required for its operations.

**All quota requests will be reviewed by the Platform Services Team and will require a proof of the need for increased resources from the product team (i.e. load test results, CPU/RAM historic usage chart that shows consistent consumption close to the limit).** 

We haven't been very efficient with using resources on the old OCP 3.11 Platform, so we are trying to get better on the new Platform :)

**Comment by StevenBarre** [comment]
OCP3 defaults were a Medium for CPU/Mem and a Large for storage.

**Comment by sbathgate** [comment]
# Walkthrough of the Quota Increase procedure
![Quota Increase](https://user-images.githubusercontent.com/30994898/102813257-5ae71a00-437d-11eb-9c47-762361957be4.gif)

**Comment by rstens** [comment]
A url would be nice

**Comment by sbathgate** [comment]
Hi @rstens, each project has a unique url which is part of the path to the quota page, so it isn't something that can necessarily be directly linked to. The url to the registry is: [https://registry.developer.gov.bc.ca/](https://registry.developer.gov.bc.ca/). The format of the link to the quota edit page would be as follows if that is helpful too:
https://registry.developer.gov.bc.ca/profile/[:uniqueProfileId]/quota

**Comment by rstens** [comment]
Thanks, that was was I was looking for.
