### ISSUE TITLE
New IP Ranges

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/OpenShift4-Migration#41]
The new cluster has a different set of IP Addresses.

RocketChat Reference(s):
- https://chat.pathfinder.gov.bc.ca/channel/devops-ocp4-migration?msg=2HniRQZCrT9eCCke4

For further details (access to the protected space in Documize is required):
https://docs.developer.gov.bc.ca/s/bn6v0ac6f9gue7hhirbg/protected-platform-services/d/bsg9q3nu3u14r4kded80/ocp-4-platform-network-topology

**Comment by mbystedt** [comment]
@garywong-bc The links need updating after the url change.

**Comment by ikethecoder** [comment]
I _think_ these are the new ones:

https://chat.developer.gov.bc.ca/channel/devops-ocp4-migration?msg=2HniRQZCrT9eCCke4

https://docs.developer.gov.bc.ca/s/bn6v0ac6f9gue7hhirbg/protected-platform-services/d/bsg9q3nu3u14r4kded80/ocp-4-prod-networks
