### ISSUE TITLE
Granting users access to Project Namespaces

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/OpenShift4-Migration#42]
In the Console GUI, first switch from `Administrator` to `Developer` mode, and on the 
`Developer` menu, select a project and then select `Project Access`.

Important, GitHub usernames need to be cast to lowercase and appended with `@github`. 
 `@github` is the specific auth provider to KeyCloak; in the future it will also support IDIR.

RocketChat Reference(s):
- https://chat.pathfinder.gov.bc.ca/channel/devops-ocp4-migration?msg=KPZj8gL375kKGELwh
- https://chat.pathfinder.gov.bc.ca/channel/devops-ocp4-migration?msg=bgprGyqhv3ZAZbC7N

**Comment by rloisell** [comment]
@garywong-bc  - casting the username in lower case is creating issues and security concerns as they are case sensitive within GitHub.com. It very easy to assign the incorrect user when in one place it is case sensitive, and in another it is not. 

CC: @NickCorcoran @mitovskaol @juhewitt
