### ISSUE TITLE
How do I add users to my namespace

### ISSUE THREAD

**Issue by jleach** [BCDevOps/OpenShift4-Migration#54]
The UI has changed but the functionality largely remains the same. To add users, admin or otherwise, using the "Administrator / Developer" drop down in the top left. Then Developer -> Project -> Project Access. Add users with `@github` after their name like `jane@github`.

![add-user](https://user-images.githubusercontent.com/390891/100473788-fbeef780-3093-11eb-939a-72f0ba77bdda.gif)

**Comment by patricksimonian** [comment]
You can also add users via the commandline: `oc policy add-role-to-user <role> <user>` for a given namespace. This will create a rolebinding in that namespace just like the above gif.
