### ISSUE TITLE
How do I request a gov.bc.ca subdomain for my app in OCP 4?

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/OpenShift4-Migration#57]
All apps hosted in OCP 4 Platforms are expected to have a gov.bc.ca subdomain (e.g. myapp.gov.bc.ca) in order to reduce their ties to the cluster-specific DNS and increase their portability within the multi-cluster OCP 4 Platform. While the wildcard DNS is now supported in the OCP 4 Silver cluster as per [#72](https://github.com/BCDevOps/OpenShift4-Migration/issues/72), it has been implemented as a temporary solution to enable the teams to move ahead with their migration while they are waiting for the iStore order for their gov.bc.ca subdomain to be processed. 

The process of request a new gov.bc.ca subdomain for CITZ projects:

1. Ask the Ministry contact for GCPE for approval on URL name
2. Order (via iStore), the SSL Certificate (Fillout a SSL request form without WAM required and attach to SSL Certificate)
Info: https://ssbc-client.gov.bc.ca/services/SSLCert/overview.htm and https://ssbc-client.gov.bc.ca/services/SSLCert/documents.htm
3. Send a note to DNSRequest@gov.bc.ca to create dns entry with new URL and point to OCP4
4. Once you receive a note from SSL folks, you will need to send them a CSR.
5. They will send you the Certificate

For everybody else,  submit a Web Property Application to the GCPE Joint Delivery Working Group as described [here](https://www2.gov.bc.ca/gov/content/governments/services-for-government/service-experience-digital-delivery/digital-delivery/web-property-process/web-property-applications).

**Comment by gil0109** [comment]
For CITZ, if you work with CITZ IMB for services, send your DNSRequest to CITZIMBTechServ@gov.bc.ca instead of DNSReqeust@gov.bc.ca
