### ISSUE TITLE
How do I move data between clusters?

### ISSUE THREAD

**Issue by jleach** [BCDevOps/OpenShift4-Migration#60]
OpenShift 4.5+ (Silver Cluster) comes with an image `openshift/cli` in the `openshift` namespace. You can spin one up on the Silver cluster, `oc logon` to the Pathfinder (3.11) cluster, and then do commands like `oc rsync` to copy data from Pathfinder to a PVC mounted on your `openshift/cli` Pod.

The command below will help you get started. If you don't want the pod to be **deleted** when it exits remove the argument `--rm=true` or set it to `--rm=false`.

```console
oc run -i -t mycli \
--image=image-registry.openshift-image-registry.svc:5000/openshift/cli:latest \
--restart=Never \
--command=true \
--rm=true \
-- /bin/bash
```

Once the pod is started you can `export HOME=/tmp` and then `oc login` as normal.

**ProTip**
You can use this container for other things like CronJobs, etc.

**Comment by jefkel** [comment]
For some templates and step by step samples for copying data between clusters, head on over to the [BCDevOps/StorageMigration/CrossClusterDataSteps](https://github.com/BCDevOps/StorageMigration/blob/master/CrossClusterDataSteps.md) walkthrough in the [StorageMigration](https://github.com/BCDevOps/StorageMigration) repo.

The walkthrough includes templates to build and deploy a migration pod (that mounts your PVC), as well as how to run an `oc rsync` from a pod in Cluster A to a pod in Cluster B.
