### ISSUE TITLE
I have accidentally deleted my artifactory-creds secret from my tools project. How can I restore it?

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/OpenShift4-Migration#63]
The long-term solution for this problem is to find the ArtifactoryServiceAccount object in your tools namespace and delete it. The project provisioner will recreate it for you.

However, at the moment, there are some privilege problems with that object where the admin of the namespace should be able to view and delete it, but cannot. We are still investigating this problem so, for the time being, please post in #devops-artifactory or #devops-ocp4-migration to ask for help with someone who has permissions to delete the object for you.

**Comment by caggles** [comment]
The solution here is to find the ArtifactoryServiceAccount object in your tools namespace and delete it. The project provisioner will recreate it for you.

However, at the moment, there are some privilege problems with that object where the admin of the namespace _should_ be able to view and delete it, but cannot. We are still investigating this problem so, for the time being, please post in #devops-artifactory or #devops-ocp4-migration to ask for help with someone who has permissions to delete the object for you.
